#!/usr/bin/env node

// Converts verification_key.json into Rust constants for groth16-solana.
const fs = require("fs");
const path = require("path");

const vkPath = path.join(__dirname, "..", "verification_key.json");
const outPath = path.join(__dirname, "..", "..", "programs", "zk_location_verifier", "src", "verifying_key.rs");

if (!fs.existsSync(vkPath)) {
  console.error("Missing verification_key.json. Run scripts/compile.sh first.");
  process.exit(1);
}

const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));

// Helper to format bigints as little-endian hex arrays for groth16-solana.
function formatField(el) {
  // groth16-solana expects big-endian bytes
  let hex = BigInt(el).toString(16);
  if (hex.length % 2) hex = "0" + hex;
  const bytes = hex.match(/.{1,2}/g).map((b) => `0x${b}`);
  const padded = Array(32 - bytes.length).fill("0x00").concat(bytes);
  return padded;
}

function formatG1([x, y]) {
  return `G1Bytes { x: [${formatField(x).join(", ")}], y: [${formatField(y).join(", ")}] }`;
}

function formatG2([[xa, xb], [ya, yb]]) {
  return `G2Bytes { x: [[${formatField(xa).join(", ")}], [${formatField(xb).join(", ")}]], y: [[${formatField(ya).join(", ")}], [${formatField(yb).join(", ")}]] }`;
}

const lines = [];
lines.push("// Auto-generated by circuits/scripts/export_vk_to_rust.js");
lines.push("use groth16_solana::groth16::VerifyingKey;");
lines.push("use groth16_solana::bn254::{G1Bytes, G2Bytes};");
lines.push("");
lines.push("pub fn verifying_key() -> VerifyingKey {");
lines.push("    VerifyingKey {");
lines.push(`        alpha_g1: ${formatG1(vk.vk_alpha_1)},`);
lines.push(`        beta_g2: ${formatG2(vk.vk_beta_2)},`);
lines.push(`        gamma_g2: ${formatG2(vk.vk_gamma_2)},`);
lines.push(`        delta_g2: ${formatG2(vk.vk_delta_2)},`);

const icArray = vk.ic || vk.IC;
if (!icArray) {
  throw new Error("verification_key.json missing IC array");
}
const ic = icArray.map((point) => formatG1(point)).join(",\n            ");
lines.push("        gamma_abc_g1: vec![");
lines.push(`            ${ic}`);
lines.push("        ],");
lines.push("    }");
lines.push("}");

fs.writeFileSync(outPath, lines.join("\n"));
console.log(`[vk] Wrote ${outPath}`);
